/*md5:702ba6f54a238eb3b73f5a5909cec18c*/
/**
 * 非常用地域，省
 */
const LastProvinces = [{
    "name": "新疆",
    "id": 471,
    "cities": [{
        "name": "阿克苏",
        "id": 472
    }, {
        "name": "阿勒泰",
        "id": 473
    }, {
        "name": "昌吉",
        "id": 476
    }, {
        "name": "哈密",
        "id": 477
    }, {
        "name": "和田",
        "id": 478
    }, {
        "name": "喀什",
        "id": 479
    }, {
        "name": "克拉玛依",
        "id": 480
    }, {
        "name": "塔城",
        "id": 483
    }, {
        "name": "吐鲁番",
        "id": 484
    }, {
        "name": "乌鲁木齐",
        "id": 485
    }, {
        "name": "伊犁",
        "id": 486
    }, {
        "name": "克孜勒苏柯尔克孜",
        "id": 602
    }, {
        "name": "博尔塔拉",
        "id": 603
    }, {
        "name": "巴音郭楞",
        "id": 604
    }, {
        "name": "五家渠",
        "id": 625
    }, {
        "name": "阿拉尔",
        "id": 626
    }]
}, {
    "name": "西藏",
    "id": 463,
    "cities": [{
        "name": "阿里",
        "id": 464
    }, {
        "name": "昌都",
        "id": 465
    }, {
        "name": "拉萨",
        "id": 466
    }, {
        "name": "林芝",
        "id": 467
    }, {
        "name": "那曲",
        "id": 468
    }, {
        "name": "日喀则",
        "id": 469
    }, {
        "name": "山南",
        "id": 470
    }]
}, {
    "name": "台湾",
    "id": 577
}, {
    "name": "香港",
    "id": 599
}, {
    "name": "澳门",
    "id": 576
}, {
    "name": "中国其他",
    "id": 531
}]

/**
 * 常用地域，按照ABCD分组省
 */
const CommonAreas = [{
    "name": "A",
    "provinces": [{
        "name": "安徽",
        "id": 1,
        "cities": [{
            "id": 2,
            "name": "安庆"
        }, {
            "id": 3,
            "name": "蚌埠"
        }, {
            "id": 4,
            "name": "巢湖"
        }, {
            "id": 5,
            "name": "池州"
        }, {
            "id": 6,
            "name": "滁州"
        }, {
            "id": 7,
            "name": "阜阳"
        }, {
            "id": 8,
            "name": "合肥"
        }, {
            "id": 9,
            "name": "淮北"
        }, {
            "id": 10,
            "name": "淮南"
        }, {
            "id": 11,
            "name": "黄山"
        }, {
            "id": 12,
            "name": "六安"
        }, {
            "id": 13,
            "name": "马鞍山"
        }, {
            "id": 14,
            "name": "宿州"
        }, {
            "id": 15,
            "name": "铜陵"
        }, {
            "id": 16,
            "name": "芜湖"
        }, {
            "id": 17,
            "name": "宣城"
        }, {
            "id": 18,
            "name": "亳州"
        }]
    }]
}, {
    "name": "B",
    "provinces": [{
        "name": "北京",
        "id": 19
    }]
}, {
    "name": "C",
    "provinces": [{
        "name": "重庆",
        "id": 532
    }]
}, {
    "name": "F",
    "provinces": [{
        "name": "福建",
        "id": 39,
        "cities": [{
            "id": 40,
            "name": "福州"
        }, {
            "id": 41,
            "name": "龙岩"
        }, {
            "id": 42,
            "name": "南平"
        }, {
            "id": 44,
            "name": "宁德"
        }, {
            "id": 45,
            "name": "莆田"
        }, {
            "id": 46,
            "name": "泉州"
        }, {
            "id": 48,
            "name": "三明"
        }, {
            "id": 50,
            "name": "厦门"
        }, {
            "id": 51,
            "name": "漳州"
        }]
    }]
}, {
    "name": "G",
    "provinces": [{
        "name": "广东",
        "id": 68,
        "cities": [{
            "id": 69,
            "name": "潮州"
        }, {
            "id": 70,
            "name": "东莞"
        }, {
            "id": 71,
            "name": "佛山"
        }, {
            "id": 73,
            "name": "广州"
        }, {
            "id": 74,
            "name": "河源"
        }, {
            "id": 75,
            "name": "惠州"
        }, {
            "id": 76,
            "name": "江门"
        }, {
            "id": 77,
            "name": "揭阳"
        }, {
            "id": 78,
            "name": "茂名"
        }, {
            "id": 79,
            "name": "梅州"
        }, {
            "id": 80,
            "name": "清远"
        }, {
            "id": 81,
            "name": "汕头"
        }, {
            "id": 83,
            "name": "汕尾"
        }, {
            "id": 84,
            "name": "韶关"
        }, {
            "id": 85,
            "name": "深圳"
        }, {
            "id": 86,
            "name": "阳江"
        }, {
            "id": 87,
            "name": "云浮"
        }, {
            "id": 88,
            "name": "湛江"
        }, {
            "id": 89,
            "name": "肇庆"
        }, {
            "id": 90,
            "name": "中山"
        }, {
            "id": 91,
            "name": "珠海"
        }]
    }, {
        "name": "广西",
        "id": 92,
        "cities": [{
            "id": 93,
            "name": "百色"
        }, {
            "id": 94,
            "name": "北海"
        }, {
            "id": 96,
            "name": "防城港"
        }, {
            "id": 98,
            "name": "桂林"
        }, {
            "id": 99,
            "name": "贵港"
        }, {
            "id": 100,
            "name": "河池"
        }, {
            "id": 102,
            "name": "贺州"
        }, {
            "id": 104,
            "name": "柳州"
        }, {
            "id": 105,
            "name": "南宁"
        }, {
            "id": 106,
            "name": "钦州"
        }, {
            "id": 107,
            "name": "梧州"
        }, {
            "id": 108,
            "name": "玉林"
        }, {
            "id": 581,
            "name": "来宾"
        }, {
            "id": 580,
            "name": "崇左"
        }]
    }, {
        "name": "贵州",
        "id": 109,
        "cities": [{
            "id": 110,
            "name": "安顺"
        }, {
            "id": 111,
            "name": "毕节"
        }, {
            "id": 112,
            "name": "贵阳"
        }, {
            "id": 113,
            "name": "六盘水"
        }, {
            "id": 117,
            "name": "铜仁"
        }, {
            "id": 118,
            "name": "遵义"
        }, {
            "id": 582,
            "name": "黔东南"
        }, {
            "id": 583,
            "name": "黔南"
        }, {
            "id": 584,
            "name": "黔西"
        }]
    }, {
        "name": "甘肃",
        "id": 52,
        "cities": [{
            "id": 53,
            "name": "白银"
        }, {
            "id": 54,
            "name": "定西"
        }, {
            "id": 55,
            "name": "嘉峪关"
        }, {
            "id": 56,
            "name": "金昌"
        }, {
            "id": 57,
            "name": "酒泉"
        }, {
            "id": 59,
            "name": "兰州"
        }, {
            "id": 60,
            "name": "临夏"
        }, {
            "id": 61,
            "name": "陇南"
        }, {
            "id": 62,
            "name": "平凉"
        }, {
            "id": 63,
            "name": "庆阳"
        }, {
            "id": 65,
            "name": "天水"
        }, {
            "id": 66,
            "name": "武威"
        }, {
            "id": 67,
            "name": "张掖"
        }, {
            "id": 579,
            "name": "甘南"
        }]
    }]
}, {
    "name": "H",
    "provinces": [{
        "name": "黑龙江",
        "id": 165,
        "cities": [{
            "id": 166,
            "name": "大庆"
        }, {
            "id": 167,
            "name": "哈尔滨"
        }, {
            "id": 169,
            "name": "鹤岗"
        }, {
            "id": 170,
            "name": "黑河"
        }, {
            "id": 173,
            "name": "鸡西"
        }, {
            "id": 174,
            "name": "佳木斯"
        }, {
            "id": 176,
            "name": "牡丹江"
        }, {
            "id": 178,
            "name": "七台河"
        }, {
            "id": 179,
            "name": "齐齐哈尔"
        }, {
            "id": 180,
            "name": "双鸭山"
        }, {
            "id": 181,
            "name": "绥化"
        }, {
            "id": 183,
            "name": "伊春"
        }, {
            "id": 622,
            "name": "大兴安岭"
        }]
    }, {
        "name": "河北",
        "id": 125,
        "cities": [{
            "id": 126,
            "name": "保定"
        }, {
            "id": 129,
            "name": "沧州"
        }, {
            "id": 132,
            "name": "承德"
        }, {
            "id": 133,
            "name": "邯郸"
        }, {
            "id": 134,
            "name": "衡水"
        }, {
            "id": 135,
            "name": "廊坊"
        }, {
            "id": 137,
            "name": "秦皇岛"
        }, {
            "id": 138,
            "name": "石家庄"
        }, {
            "id": 140,
            "name": "唐山"
        }, {
            "id": 141,
            "name": "邢台"
        }, {
            "id": 144,
            "name": "张家口"
        }]
    }, {
        "name": "河南",
        "id": 145,
        "cities": [{
            "id": 146,
            "name": "安阳"
        }, {
            "id": 147,
            "name": "鹤壁"
        }, {
            "id": 148,
            "name": "焦作"
        }, {
            "id": 149,
            "name": "开封"
        }, {
            "id": 150,
            "name": "洛阳"
        }, {
            "id": 151,
            "name": "南阳"
        }, {
            "id": 152,
            "name": "平顶山"
        }, {
            "id": 153,
            "name": "三门峡"
        }, {
            "id": 155,
            "name": "商丘"
        }, {
            "id": 156,
            "name": "新乡"
        }, {
            "id": 157,
            "name": "信阳"
        }, {
            "id": 159,
            "name": "许昌"
        }, {
            "id": 160,
            "name": "郑州"
        }, {
            "id": 161,
            "name": "周口"
        }, {
            "id": 162,
            "name": "驻马店"
        }, {
            "id": 163,
            "name": "漯河"
        }, {
            "id": 164,
            "name": "濮阳"
        }, {
            "id": 621,
            "name": "济源"
        }]
    }, {
        "name": "湖北",
        "id": 184,
        "cities": [{
            "id": 185,
            "name": "鄂州"
        }, {
            "id": 186,
            "name": "恩施"
        }, {
            "id": 188,
            "name": "黄冈"
        }, {
            "id": 191,
            "name": "黄石"
        }, {
            "id": 192,
            "name": "荆门"
        }, {
            "id": 193,
            "name": "荆州"
        }, {
            "id": 196,
            "name": "十堰"
        }, {
            "id": 198,
            "name": "随州"
        }, {
            "id": 200,
            "name": "武汉"
        }, {
            "id": 203,
            "name": "咸宁"
        }, {
            "id": 205,
            "name": "襄樊"
        }, {
            "id": 207,
            "name": "孝感"
        }, {
            "id": 210,
            "name": "宜昌"
        }, {
            "id": 623,
            "name": "潜江"
        }, {
            "id": 624,
            "name": "神农架"
        }, {
            "id": 199,
            "name": "天门"
        }, {
            "id": 202,
            "name": "仙桃"
        }]
    }, {
        "name": "湖南",
        "id": 212,
        "cities": [{
            "id": 213,
            "name": "常德"
        }, {
            "id": 214,
            "name": "长沙"
        }, {
            "id": 215,
            "name": "郴州"
        }, {
            "id": 216,
            "name": "衡阳"
        }, {
            "id": 218,
            "name": "怀化"
        }, {
            "id": 220,
            "name": "娄底"
        }, {
            "id": 223,
            "name": "邵阳"
        }, {
            "id": 224,
            "name": "湘潭"
        }, {
            "id": 227,
            "name": "益阳"
        }, {
            "id": 228,
            "name": "永州"
        }, {
            "id": 230,
            "name": "岳阳"
        }, {
            "id": 232,
            "name": "张家界"
        }, {
            "id": 233,
            "name": "株洲"
        }, {
            "id": 585,
            "name": "湘西"
        }]
    }, {
        "name": "海南",
        "id": 120,
        "cities": [{
            "id": 121,
            "name": "海口"
        }, {
            "id": 122,
            "name": "三亚"
        }, {
            "id": 609,
            "name": "白沙"
        }, {
            "id": 610,
            "name": "昌江"
        }, {
            "id": 611,
            "name": "澄迈"
        }, {
            "id": 612,
            "name": "定安"
        }, {
            "id": 613,
            "name": "东方"
        }, {
            "id": 614,
            "name": "乐东"
        }, {
            "id": 615,
            "name": "琼海"
        }, {
            "id": 616,
            "name": "万宁"
        }, {
            "id": 617,
            "name": "文昌"
        }, {
            "id": 618,
            "name": "五指山"
        }, {
            "id": 619,
            "name": "保亭"
        }, {
            "id": 620,
            "name": "陵水"
        }]
    }]
}, {
    "name": "J",
    "provinces": [{
        "name": "吉林",
        "id": 234,
        "cities": [{
            "id": 235,
            "name": "白城"
        }, {
            "id": 237,
            "name": "白山"
        }, {
            "id": 238,
            "name": "长春"
        }, {
            "id": 239,
            "name": "吉林"
        }, {
            "id": 241,
            "name": "辽源"
        }, {
            "id": 242,
            "name": "四平"
        }, {
            "id": 244,
            "name": "松原"
        }, {
            "id": 246,
            "name": "通化"
        }, {
            "id": 249,
            "name": "延边朝鲜族自治州"
        }]
    }, {
        "name": "江苏",
        "id": 255,
        "cities": [{
            "id": 256,
            "name": "常州"
        }, {
            "id": 257,
            "name": "淮安"
        }, {
            "id": 259,
            "name": "连云港"
        }, {
            "id": 260,
            "name": "南京"
        }, {
            "id": 261,
            "name": "南通"
        }, {
            "id": 262,
            "name": "苏州"
        }, {
            "id": 265,
            "name": "宿迁"
        }, {
            "id": 266,
            "name": "泰州"
        }, {
            "id": 269,
            "name": "无锡"
        }, {
            "id": 272,
            "name": "徐州"
        }, {
            "id": 273,
            "name": "盐城"
        }, {
            "id": 275,
            "name": "扬州"
        }, {
            "id": 277,
            "name": "镇江"
        }]
    }, {
        "name": "江西",
        "id": 279,
        "cities": [{
            "id": 280,
            "name": "抚州"
        }, {
            "id": 282,
            "name": "赣州"
        }, {
            "id": 283,
            "name": "吉安"
        }, {
            "id": 285,
            "name": "景德镇"
        }, {
            "id": 286,
            "name": "九江"
        }, {
            "id": 288,
            "name": "南昌"
        }, {
            "id": 289,
            "name": "萍乡"
        }, {
            "id": 290,
            "name": "上饶"
        }, {
            "id": 291,
            "name": "新余"
        }, {
            "id": 292,
            "name": "宜春"
        }, {
            "id": 293,
            "name": "鹰潭"
        }]
    }]
}, {
    "name": "L",
    "provinces": [{
        "name": "辽宁",
        "id": 294,
        "cities": [{
            "id": 295,
            "name": "鞍山"
        }, {
            "id": 297,
            "name": "本溪"
        }, {
            "id": 298,
            "name": "朝阳"
        }, {
            "id": 300,
            "name": "大连"
        }, {
            "id": 303,
            "name": "丹东"
        }, {
            "id": 304,
            "name": "抚顺"
        }, {
            "id": 305,
            "name": "阜新"
        }, {
            "id": 306,
            "name": "葫芦岛"
        }, {
            "id": 308,
            "name": "锦州"
        }, {
            "id": 309,
            "name": "辽阳"
        }, {
            "id": 310,
            "name": "盘锦"
        }, {
            "id": 311,
            "name": "沈阳"
        }, {
            "id": 312,
            "name": "铁岭"
        }, {
            "id": 314,
            "name": "营口"
        }]
    }]
}, {
    "name": 'N',
    "provinces": [{
        "name": "内蒙古",
        "id": 333,
        "cities": [{
            "id": 321,
            "name": "呼伦贝尔"
        }, {
            "id": 328,
            "name": "阿拉善"
        }, {
            "id": 336,
            "name": "包头"
        }, {
            "id": 337,
            "name": "赤峰"
        }, {
            "id": 339,
            "name": "呼和浩特"
        }, {
            "id": 344,
            "name": "通辽"
        }, {
            "id": 346,
            "name": "乌海"
        }, {
            "id": 586,
            "name": "鄂尔多斯"
        }, {
            "id": 587,
            "name": "乌兰察布"
        }, {
            "id": 588,
            "name": "巴彦淖尔"
        }, {
            "id": 589,
            "name": "兴安盟"
        }, {
            "id": 590,
            "name": "锡林郭勒"
        }]
    }, {
        "name": "宁夏",
        "id": 351,
        "cities": [{
            "id": 352,
            "name": "固原"
        }, {
            "id": 353,
            "name": "石嘴山"
        }, {
            "id": 354,
            "name": "吴忠"
        }, {
            "id": 356,
            "name": "银川"
        }, {
            "id": 591,
            "name": "中卫"
        }]
    }]
}, {
    "name": "Q",
    "provinces": [{
        "name": "青海",
        "id": 357,
        "cities": [{
            "id": 361,
            "name": "海东"
        }, {
            "id": 366,
            "name": "西宁"
        }, {
            "id": 367,
            "name": "玉树"
        }, {
            "id": 592,
            "name": "海北"
        }, {
            "id": 593,
            "name": "海南"
        }, {
            "id": 594,
            "name": "黄南"
        }, {
            "id": 595,
            "name": "果洛"
        }, {
            "id": 596,
            "name": "海西"
        }]
    }]
}, {
    "name": "S",
    "provinces": [{
        "name": "山西",
        "id": 393,
        "cities": [{
            "id": 394,
            "name": "长治"
        }, {
            "id": 395,
            "name": "大同"
        }, {
            "id": 396,
            "name": "晋城"
        }, {
            "id": 398,
            "name": "临汾"
        }, {
            "id": 401,
            "name": "朔州"
        }, {
            "id": 402,
            "name": "太原"
        }, {
            "id": 403,
            "name": "忻州"
        }, {
            "id": 404,
            "name": "阳泉"
        }, {
            "id": 405,
            "name": "运城"
        }, {
            "id": 597,
            "name": "晋中"
        }, {
            "id": 598,
            "name": "吕梁"
        }]
    }, {
        "name": "陕西",
        "id": 406,
        "cities": [{
            "id": 407,
            "name": "安康"
        }, {
            "id": 408,
            "name": "宝鸡"
        }, {
            "id": 409,
            "name": "汉中"
        }, {
            "id": 410,
            "name": "商洛"
        }, {
            "id": 411,
            "name": "铜川"
        }, {
            "id": 412,
            "name": "渭南"
        }, {
            "id": 413,
            "name": "西安"
        }, {
            "id": 414,
            "name": "咸阳"
        }, {
            "id": 415,
            "name": "延安"
        }, {
            "id": 416,
            "name": "榆林"
        }]
    }, {
        "name": "山东",
        "id": 368,
        "cities": [{
            "id": 369,
            "name": "滨州"
        }, {
            "id": 370,
            "name": "德州"
        }, {
            "id": 371,
            "name": "东营"
        }, {
            "id": 372,
            "name": "菏泽"
        }, {
            "id": 373,
            "name": "济南"
        }, {
            "id": 374,
            "name": "济宁"
        }, {
            "id": 376,
            "name": "莱芜"
        }, {
            "id": 377,
            "name": "聊城"
        }, {
            "id": 379,
            "name": "临沂"
        }, {
            "id": 380,
            "name": "青岛"
        }, {
            "id": 381,
            "name": "日照"
        }, {
            "id": 382,
            "name": "泰安"
        }, {
            "id": 384,
            "name": "威海"
        }, {
            "id": 386,
            "name": "潍坊"
        }, {
            "id": 389,
            "name": "烟台"
        }, {
            "id": 390,
            "name": "枣庄"
        }, {
            "id": 392,
            "name": "淄博"
        }]
    }, {
        "id": 417,
        "name": "上海"
    }, {
        "name": "四川",
        "id": 438,
        "cities": [{
            "id": 440,
            "name": "巴中"
        }, {
            "id": 441,
            "name": "成都"
        }, {
            "id": 442,
            "name": "达州"
        }, {
            "id": 443,
            "name": "德阳"
        }, {
            "id": 444,
            "name": "甘孜藏族自治州"
        }, {
            "id": 445,
            "name": "广安"
        }, {
            "id": 447,
            "name": "广元"
        }, {
            "id": 448,
            "name": "乐山"
        }, {
            "id": 450,
            "name": "眉山"
        }, {
            "id": 451,
            "name": "绵阳"
        }, {
            "id": 452,
            "name": "南充"
        }, {
            "id": 453,
            "name": "内江"
        }, {
            "id": 454,
            "name": "攀枝花"
        }, {
            "id": 455,
            "name": "遂宁"
        }, {
            "id": 456,
            "name": "雅安"
        }, {
            "id": 457,
            "name": "宜宾"
        }, {
            "id": 458,
            "name": "资阳"
        }, {
            "id": 459,
            "name": "自贡"
        }, {
            "id": 460,
            "name": "泸州"
        }, {
            "id": 600,
            "name": "凉山"
        }, {
            "id": 601,
            "name": "阿坝"
        }]
    }]
}, {
    "name": "T",
    "provinces": [{
        "name": "天津",
        "id": 461
    }]
}, {
    "name": "Y",
    "provinces": [{
        "name": "云南",
        "id": 488,
        "cities": [{
            "id": 489,
            "name": "保山"
        }, {
            "id": 490,
            "name": "楚雄"
        }, {
            "id": 491,
            "name": "大理"
        }, {
            "id": 492,
            "name": "德宏"
        }, {
            "id": 497,
            "name": "昆明"
        }, {
            "id": 499,
            "name": "丽江"
        }, {
            "id": 500,
            "name": "临沧"
        }, {
            "id": 502,
            "name": "曲靖"
        }, {
            "id": 503,
            "name": "普洱"
        }, {
            "id": 504,
            "name": "文山"
        }, {
            "id": 506,
            "name": "玉溪"
        }, {
            "id": 507,
            "name": "昭通"
        }, {
            "id": 605,
            "name": "西双版纳"
        }, {
            "id": 606,
            "name": "红河"
        }, {
            "id": 607,
            "name": "怒江"
        }, {
            "id": 608,
            "name": "迪庆"
        }]
    }]
}, {
    "name": "Z",
    "provinces": [{
        "name": "浙江",
        "id": 508,
        "cities": [{
            "id": 509,
            "name": "杭州"
        }, {
            "id": 511,
            "name": "湖州"
        }, {
            "id": 512,
            "name": "嘉兴"
        }, {
            "id": 514,
            "name": "金华"
        }, {
            "id": 518,
            "name": "丽水"
        }, {
            "id": 519,
            "name": "宁波"
        }, {
            "id": 522,
            "name": "绍兴"
        }, {
            "id": 523,
            "name": "台州"
        }, {
            "id": 526,
            "name": "温州"
        }, {
            "id": 528,
            "name": "舟山"
        }, {
            "id": 529,
            "name": "衢州"
        }]
    }]
}]

let ProvinceMap = {},
    CityMap = {},
    DefaultSelected = []; //默认选中常用

let Wrap = (province) => {
    // JSON.parse(JSON.stringify(province)) 简单深拷贝
    ProvinceMap[province.id] = JSON.parse(JSON.stringify(province));
    province.cities = province.cities || [];
    province.cities.forEach(city => {
        CityMap[city.id] = {
            ...city,
            province: JSON.parse(JSON.stringify(province))
        }
    })
}

LastProvinces.forEach(province => {
    Wrap(province);
})

CommonAreas.forEach(area => {
    area.provinces.forEach(province => {
        // 默认选中常用地域
        DefaultSelected.push(province.id);

        Wrap(province);
    })

})

export = {
    provinceMap: ProvinceMap,
    cityMap: CityMap,
    commonAreas: CommonAreas,
    lastProvinces: LastProvinces,
    defaultSelected: DefaultSelected
}