/*md5:b7032e82ab1a7470e2da0fb287d326bd*/
module.exports = {
    "secradio.expand": "Expand",
    "secradio.collapse": "Collapse",
    "calendar.before.yesterday": "The day before yesterday",
    "calendar.dynamic.end": "End of {day} days",
    "calendar.dynamic.end.tip": "End of {day} days（base of begin time）",
    "calendar.forever": "Not limited",
    "calendar.forever.tip": "No limit to the end time",
    "calendar.friday": "Fri",
    "calendar.last.month": "Last month",
    "calendar.last.week": "Last week",
    "calendar.last.week.monday": "Last week（Monday to Sunday）",
    "calendar.last.week.sunday": "Last week（Sunday to Saturday）",
    "calendar.lastest": "Lastest",
    "calendar.monday": "Mon",
    "calendar.n.arbitrary": "n can be an arbitrary integer",
    "calendar.natural.month": "End of natural month",
    "calendar.natural.month.tip": "End of natural month",
    "calendar.next.month": "End of next month",
    "calendar.next.month.tip": "End of next month",
    "calendar.passed": "Passed",
    "calendar.quick": "Quick date",
    "calendar.range.title": "Please select a date",
    "calendar.saturday": "Sat",
    "calendar.sunday": "Sun",
    "calendar.this.month": "This month",
    "calendar.this.month.today": "This month（start from today）",
    "calendar.this.month.yestarday": "This month（start from yestarday）",
    "calendar.this.week": "This week",
    "calendar.this.week.monday": "This week（Monday to Sunday）",
    "calendar.this.week.sunday": "This week（Sunday to Saturday）",
    "calendar.thursday": "Thur",
    "calendar.to": "to",
    "calendar.today": "Today",
    "calendar.tuesday": "Tues",
    "calendar.unit": "days",
    "calendar.unit.today": "days（end of today）",
    "calendar.unit.yesterday": "days（end of yesterday）",
    "calendar.vs": "vs",
    "calendar.wednesday": "Wed",
    "calendar.yesterday": "Yesterday",
    "calendar.tomorrow": "Tomorrow",
    "dropdown.all.custom": "All",
    "dropdown.search": "Search",
    "form.char": "characters",
    "form.char.between": "Between {min} to {max} characters, current: {current} characters",
    "form.check.chinese": "Please enter the Chinese",
    "form.check.currency": "Please enter the amount, accurate to two decimal places",
    "form.check.english": "Please enter the English",
    "form.check.email": "Please enter the correct email address",
    "form.check.equal": "Equal to {rule}",
    "form.check.unequal": "Unequal to {rule}",
    "form.check.int": "Please enter an integer",
    "form.check.json": "Please enter a valid JSON",
    "form.check.mobile": "Please enter the correct phone number",
    "form.check.landline": "Please enter the correct setphone",
    "form.check.phone": "Please enter the correct phone number",
    "form.check.negint": "Please enter a negative integer",
    "form.check.number": "Please enter a number",
    "form.check.pattern": "Wrong pattern",
    "form.check.posint": "Please enter a positive integer",
    "form.check.required": "Required",
    "form.check.trim": "Can't be contain spaces",
    "form.check.url": "The URL is not in the correct format",
    "form.less": "At least",
    "form.check.range": "Please enter a number between {min} and {max}, , including {min} and {max}",
    "form.check.range.border": "Please enter a number between {min} and {max}, , not including {min} and {max}",
    "form.max": "Please enter a number less than or equal to {max}",
    "form.max.border": "Please enter a number less than {max}",
    "form.min": "Please enter a number greater than or equal to {min}",
    "form.min.border": "Please enter a number greater than {min}",
    "form.more": "Up to",
    "form.word": "words",
    "form.word.between": "Between {min} to {max} words, current: {current} words",
    "pager.offset": "{min} - {max} of ",
    "pager.per.page": "",
    "pager.total": "{total} items",
    "pager.unit": "items per page",
    "pager.jump.to": "jump to page",
    "pager.jump.unit": "",
    "dialog.title": "Notice",
    "dialog.cancel": "Cancel",
    "dialog.submit": "Submit",
    "select.all": "Select all",
    "unselect.all": "Unselect all",
    "search": "Search",
    "choose": "Choose please",
    "empty.text": "No match",
    "tab.add.name": "New Tab",
};