/*md5:20bbe8f20d63e6575af152f7aedf2502*/
module.exports = {
    "secradio.expand": "一键展开",
    "secradio.collapse": "一键收起",
    "calendar.before.yesterday": "前天",
    "calendar.dynamic.end": "{day}天后结束",
    "calendar.dynamic.end.tip": "{day}天后结束（以开始时间为准动态计算）",
    "calendar.forever": "不限",
    "calendar.forever.tip": "有开始时间，结束时间不限",
    "calendar.friday": "五",
    "calendar.last.month": "上月",
    "calendar.last.week": "上周",
    "calendar.last.week.monday": "上周（周一至周日）",
    "calendar.last.week.sunday": "上周（周日至周六）",
    "calendar.lastest": "最近",
    "calendar.monday": "一",
    "calendar.n.arbitrary": "n可为任意整数",
    "calendar.natural.month": "自然月月底结束",
    "calendar.natural.month.tip": "开始时间到开始时间所在月月底",
    "calendar.next.month": "次月月底结束",
    "calendar.next.month.tip": "开始时间到开始时间次月月底",
    "calendar.passed": "过去",
    "calendar.quick": "快捷日期",
    "calendar.range.title": "选择日期",
    "calendar.saturday": "六",
    "calendar.sunday": "日",
    "calendar.this.month": "本月",
    "calendar.this.month.today": "本月（今日开始算）",
    "calendar.this.month.yestarday": "本月（昨日开始算）",
    "calendar.this.week": "本周",
    "calendar.this.week.monday": "本周（周一开始，包含今日）",
    "calendar.this.week.sunday": "本周（周日开始，包含今日）",
    "calendar.thursday": "四",
    "calendar.to": "至",
    "calendar.today": "今日",
    "calendar.tuesday": "二",
    "calendar.unit": "天",
    "calendar.unit.today": "天（今日开始算）",
    "calendar.unit.yesterday": "天（昨日开始算）",
    "calendar.vs": "对比",
    "calendar.wednesday": "三",
    "calendar.yesterday": "昨日",
    "calendar.tomorrow": "明日",
    "dropdown.all.custom": "全部",
    "dropdown.search": "搜索关键词",
    "form.char": "个字符",
    "form.char.between": "{min} ~ {max} 个字符之间，当前：{current}",
    "form.check.chinese": "请输入中文",
    "form.check.currency": "请输入金额，精确到小数点后两位",
    "form.check.english": "请输入英文",
    "form.check.email": "请输入正确的邮箱地址",
    "form.check.equal": "请输入与 {rule} 相同的内容",
    "form.check.unequal": "请输入与 {rule} 不同的内容",
    "form.check.int": "请输入整数",
    "form.check.json": "请输入合法的JSON",
    "form.check.mobile": "请输入正确的手机号码",
    "form.check.landline": "请输入正确的固定电话号码",
    "form.check.phone": "请输入正确的手机号码或者固定电话号码",
    "form.check.negint": "请输入负整数",
    "form.check.number": "请输入数字",
    "form.check.pattern": "格式有误",
    "form.check.posint": "请输入正整数",
    "form.check.required": "必填",
    "form.check.trim": "不能包含空格",
    "form.check.url": "url格式不正确",
    "form.less": "最少",
    "form.check.range": "请输入 {min} ~ {max} 之间的数字，包含 {min} 和 {max}",
    "form.check.range.border": "请输入 {min} ~ {max} 之间的数字，不包含 {min} 和 {max}",
    "form.max": "请输入小于等于 {max} 的数字",
    "form.max.border": "请输入小于 {max} 的数字",
    "form.min": "请输入大于等于 {min} 的数字",
    "form.min.border": "请输入大于 {min} 的数字",
    "form.more": "最多",
    "form.word": "个字",
    "form.word.between": "{min} ~ {max} 个字之间，当前：{current} 个字",
    "pager.offset": "当前第 {min} - {max} 条，",
    "pager.per.page": "每页显示",
    "pager.total": "共 {total} 条",
    "pager.unit": "条",
    "pager.jump.to": "向第",
    "pager.jump.unit": "页",
    "dialog.title": "提示",
    "dialog.cancel": "取消",
    "dialog.submit": "确定",
    "select.all": "全选",
    "unselect.all": "清空",
    "search": "搜索",
    "choose": "请选择",
    "empty.text": "无匹配内容",
    "tab.add.name": "模块",
};